{% set version = '1.2-11' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tcltk2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tcltk2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tcltk2/tcltk2_{{ version }}.tar.gz
  sha256: ad183ae3b7190501504a0589e0b3be480f04267303e3384fef00987446a37dc5

build:
  number: 1007
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('tcltk2')"           # [not win]
    - "\"%R%\" -e \"library('tcltk2')\""  # [win]

about:
  home: http://www.sciviews.org/SciViews-R
  license: LGPL-3.0-only
  summary: 'A series of additional Tcl commands and Tk widgets with style and various functions
    (under Windows: DDE exchange, access to the registry and icon manipulation) to supplement
    the tcltk package'
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: tcltk2
# Type: Package
# Version: 1.2-11
# Date: 2014-12-19
# Title: Tcl/Tk Additions
# Author: Philippe Grosjean [aut, cre]
# Authors@R: c(person("Philippe", "Grosjean", role = c("aut", "cre"), email = "phgrosjean@sciviews.org"))
# Maintainer: Philippe Grosjean <phgrosjean@sciviews.org>
# Depends: R (>= 2.8.0), tcltk
# Suggests: utils
# SystemRequirements: Tcl/Tk (>= 8.5), Tktable (>= 2.9, optional)
# Description: A series of additional Tcl commands and Tk widgets with style and various functions (under Windows: DDE exchange, access to the registry and icon manipulation) to supplement the tcltk package
# License: LGPL-3 + file LICENSE
# URL: http://www.sciviews.org/SciViews-R
# BugReports: https://r-forge.r-project.org/tracker/?group_id=194
# Packaged: 2014-12-19 16:32:30 UTC; phgrosjean
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-12-20 10:35:06
