travis:
  secure:
    BINSTAR_TOKEN: nZwZyOYborkloSH7OekCLQyL6jjWnvq6s6fdNcMz3n0N1YsDQSW5VG+TQrlonrWmBdVghBpkmXoJMNFkuyB5md2mahcsJIUekml/61m/sXPIGWpjcchE/mFkOBkt+OG400Z9Tc04Mj0uCZz+maTFTPV3zFONBc6IdjnKfTwPkzrrlT5i7tOeWGbrWMbdzb2vu98ohQj7bxFIryvsWyVxXigDypBLsxq4+05Skwuc2sbCaX2xMQubxzqbsiVtxKrG3H33ITo0kLciADy+IQFRJJsAFChXqKfvAY5USh4lHTT4hHFeEsNlgwOmRcsQUgdQ7TkMfYV3WfyiV0pWTdnXHpoDXluU5J1acFVl26ubNLfIiBv2taudr8Tbfvg115jZWECehTjksaEpdP0jubBW9HMACS6JYtA301buKTP1iThl8OZniAfau9uCGVx1v8mQjGVEwFDHHxUe7rQF+J3wQocSMCJKjr0nb48v9eYzfZZLh7YJhrR15QsJgj1evh7arGzRyySsPk5lfCa3Hzk62jqQhPF/7pX6Uj5fYBuQFGnrq2E8hQp+ZBBK8f+nhtjAb9tv7ur9rKq1s2o3yySN7dp2L0ctbZ7ljiSMfeUY99eAPGDo7O99DdWw9FO9wkKBA9us3pnE3+7mdAhmFwj1U0OYP5JMCkX96dg4jCBxbE4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
