travis:
  secure:
    BINSTAR_TOKEN: lKA056TqXi8kNb+Md4sV7tfJvAwup0lDGZ1AXfiQFn/LYiF5MzBEvtrjOCyKrhk5MFhfkt2y6AtEVeba3AytHEDcoZsVUVPSxYK5Vza6RQjnBitLnkaaDB7eROkRSBH/b+IuW5rt4gXE3y38ibQ5EckI6PcsDQXB7t6bY9jDhhNyxik9+2fCm7Q2Ic/Xb+WrzpnM3ttO0zmoFVKYCrCneKfIjHsnJ4dObXaebyVAFZBdPIuyfrYaIhY7HCVc7uwIi58G/W3tGReuk0xbOG5yKlffsOkpqEZhZPcbkx/FWeIpQDnwVR4ENwwjGSD1UPddnzN9JgRdFPe6O5TYrcmi59PbmhOleNxTnpwTitpAXKb1jf5394kWCjCzQJwphVvOhWjgN+hl3F6Gb/nHj9YKJ4MWEwzczTP7nu2Be4O1KFydjdGSFnekMlkGQUDoDqqBqZ5QNe6avZ2ac6zZ51nuLSKDA6oLW749Q1cyKEpMwvYrZXocM4zBCXnp9CxNkQe97lrA+LsnVp7MGYGyTMALqZBL2PwD9lpAJTDXQ3HkDLhBX91wIs4h0f/qjKZUWdgHR1Xjqe8e7cfSfi22neRI1hZYU7H8evXoMgOmNzPGhlyh0oupPTAEEjK/b/cYEGKs5jsSaQVbsFoLuV4bOttBERXEoO89uztFz/qyHjNFq/8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
